// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		//input: N
		int N = Integer.parseInt(args[0]);
		
		int lessOrEqual = 0;
		int greater = 0;

		for (int i = 0; i < N; i++) {
			double r = Math.random();

			if (r <= 0.5) {
				lessOrEqual++;
            } else {
                greater++;

			}
		}
			if (lessOrEqual == 0 || greater == 0) {
			System.out.println("> 0.5: " + greater + " times");
			System.out.println("<= 0.5: " + lessOrEqual + " times");
		} 	else {
			double ratio = (double) greater / lessOrEqual;
			System.out.println("% java TestRandom" + " " + N );
			System.out.println("> 0.5: " + greater + " times");
			System.out.println("<= 0.5: " + lessOrEqual + " times");
			System.out.println("Ratio: " + ratio);
		}
		

	}
}
